spring:
  datasource:
    url: jdbc:h2:mem:eazybank2
    driverClassName: org.h2.Driver
    username: sa
    password: ${DB_PASS:}
    database-platform: org.hibernate.dialect.H2Dialect

  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml

  h2:
    console:
      enabled: true

default:
  admin:
    username: admin@springsecurebasic.net
    password: $2a$10$RgG9AcJGEs5b6AvAPrZoFOAFiacb7EYc50EgF6lWcmjuLNwJ.JLm6
