server:
  port: 8443
  ssl:
    enable: true
    key-store: src/main/resources/certificates/springsecury.p12
    key-store-password:
    keyStoreType: PKCS12
    keyAlias: springsecurity

spring:
  datasource:
    url: jdbc:h2:mem:eazybank2
    driverClassName: org.h2.Driver
    username: sa
    password:
    database-platform: org.hibernate.dialect.H2Dialect

  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml

default:
  admin:
    username: admin@springsecurebasic.net
    password:
