server:
  port: 8443
  ssl:
    enable: true
    key-store: src/main/resources/certificates/springsecureapp.p12
    key-store-password:
    keyStoreType: PKCS12
    keyAlias: springsecureapp

application:
  allowCORS:
    urls: https://localhost:3243